const mongoose = require('mongoose')

const VitalsSchema = new mongoose.Schema({
  bp:     String,   // "120/80"
  hr:     Number,   // bpm
  temp:   Number,   // Celsius
  spo2:   Number,   // %
  weight: Number,   // kg
  height: Number,   // cm
}, { _id: false })

const ConsultationSchema = new mongoose.Schema({
  consultId: {
    type: String, unique: true,
    default: () => 'C' + Date.now().toString().slice(-6),
  },
  patient:     { type: mongoose.Schema.Types.ObjectId, ref: 'Patient', required: true },
  doctor:      { type: mongoose.Schema.Types.ObjectId, ref: 'Doctor',  required: true },
  appointment: { type: mongoose.Schema.Types.ObjectId, ref: 'Appointment' },

  date:      { type: Date, default: Date.now },
  vitals:    VitalsSchema,
  symptoms:  { type: String, required: true },
  diagnosis: { type: String, required: true },
  notes:     { type: String },
  plan:      { type: String },

  // Attached lab/imaging results
  attachments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'MedicalRecord' }],

  // SOAP summary generated by AI
  aiSoapSummary: { type: String },
  aiGeneratedAt: { type: Date },

  followUpDate: { type: Date },
  isFollowUp:   { type: Boolean, default: false },

}, { timestamps: true })

ConsultationSchema.index({ patient: 1, date: -1 })
ConsultationSchema.index({ doctor: 1, date: -1 })

module.exports = mongoose.model('Consultation', ConsultationSchema)
