export { Dashboard } from './Dashboard'
export { Patients } from './Patients'
export { Doctors } from './Doctors'
export { Appointments } from './Appointments'
export { Prescriptions } from './Prescriptions'
export { Consultation } from './Consultations'
export { Records } from './Records'
export { Billing } from './Billing'
export { AIAssistant } from './AIAssistant'
export { Notifications, Settings, Search } from './MiscPages'
